### ISSUE TITLE
Is attention map flipped?

### ISSUE THREAD

**Issue by dneirfi** [jeongukjae/CLIP-self-attention-visualization#1]
Hi :)

I have a question about your result of self attention map visualization.

I think the attention map is flipped upside down. 
It happens to my case too. 
I wonder why it happens.

Thanks!

**Comment by jeongukjae** [comment]
Thanks!!!

I misused matplotlib 😅.
The reason for this problem is the differences in coordination system in `pcolor` and `imshow`.

--

한국분인것 같아서 편하게 써보면..
예전에 너무 빠르게 작성해서 이런 부분 체크를 제대로 못했네요.
matplotlib에서 각 함수의 좌표방식이 달라서 이런 문제가 생겼어요.
너무 감사합니다!

**Comment by jeongukjae** [comment]
resolved by https://github.com/jeongukjae/CLIP-self-attention-visualization/commit/3a04d2040c1d4bb5a383f3364b38aef927ad600c

**Comment by dneirfi** [comment]
빠른 피드백 감사합니다!
덕분에 저도 해결했습니다!
